   SET SERVEROUTPUT ON;


--part 1 
---tabel log
create table debug_log (
   log_id      number generated by default as identity primary key,
   log_time    timestamp default systimestamp,
   module_name varchar2(100),
   line_no     number,
   log_level   varchar2(10),
   log_message varchar2(4000),
   session_id  varchar2(50) default sys_context(
      'USERENV',
      'SESSIONID'
   )
);


---pachet debug
create or replace package debug_utils as
   g_debug_mode boolean := false;
   procedure enable_debug;
   procedure disable_debug;

   procedure log_msg (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_message     in varchar2
   );

   procedure log_variable (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_name        in varchar2,
      p_value       in varchar2
   );

   procedure log_error (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_error_msg   in varchar2
   );
end debug_utils;
/


---body pachet debug
create or replace package body debug_utils as

   procedure enable_debug is
   begin
      g_debug_mode := true;
   end enable_debug;

   procedure disable_debug is
   begin
      g_debug_mode := false;
   end disable_debug;

   procedure log_msg (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_message     in varchar2
   ) is
   begin
      if g_debug_mode then
         insert into debug_log (
            module_name,
            line_no,
            log_level,
            log_message
         ) values ( p_module_name,
                    p_line_no,
                    p_log_level,
                    p_message );
      end if;
   end log_msg;

   procedure log_variable (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_name        in varchar2,
      p_value       in varchar2
   ) is
   begin
      if g_debug_mode then
         insert into debug_log (
            module_name,
            line_no,
            log_level,
            log_message
         ) values ( p_module_name,
                    p_line_no,
                    p_log_level,
                    'Variable "'
                    || p_name
                    || '" = '
                    || p_value );
      end if;
   end log_variable;

   procedure log_error (
      p_module_name in varchar2,
      p_line_no     in number,
      p_log_level   in varchar2,
      p_error_msg   in varchar2
   ) is
   begin
      if g_debug_mode then
         insert into debug_log (
            module_name,
            line_no,
            log_level,
            log_message
         ) values ( p_module_name,
                    p_line_no,
                    p_log_level,
                    'ERROR: ' || p_error_msg );
      end if;
   end log_error;

end debug_utils;
/

---tabela angajati cu campurile specificate
create table employees (
   employee_id    number(6) not null,
   first_name     varchar2(20),
   last_name      varchar2(25) not null,
   email          varchar2(50) not null,
   phone_number   varchar2(20),
   hire_date      date not null,
   job_id         varchar2(10) not null,
   salary         number(8,2),
   commission_pct number(2,2),
   manager_id     number(6),
   department_id  number(4),
   constraint employees_pk primary key ( employee_id )
);


---mock data
insert into employees values ( 1001,
                               'John',
                               'Doe',
                               'john.doe@email.com',
                               '0712345678',
                               date '2022-01-15',
                               'DEV',
                               5000.00,
                               null,
                               101,
                               10 );

insert into employees values ( 1002,
                               'Alice',
                               'Smith',
                               'alice.smith@email.com',
                               '0723456789',
                               date '2021-06-20',
                               'HR',
                               4500.00,
                               0.10,
                               102,
                               20 );

insert into employees values ( 1003,
                               'Bob',
                               'Johnson',
                               'bob.johnson@email.com',
                               null,
                               date '2020-03-10',
                               'DEV',
                               6000.00,
                               null,
                               101,
                               10 );

insert into employees values ( 1004,
                               'Emma',
                               'Brown',
                               'emma.brown@email.com',
                               '0734567890',
                               date '2023-07-01',
                               'SALES',
                               4000.00,
                               0.15,
                               103,
                               30 );

insert into employees values ( 1005,
                               'Liam',
                               'Davis',
                               'liam.davis@email.com',
                               '0745678901',
                               date '2019-11-25',
                               'FIN',
                               7000.00,
                               null,
                               104,
                               40 );

insert into employees values ( 1006,
                               'Michael',
                               'Taylor',
                               'michael.taylor@email.com',
                               '0751111111',
                               date '2022-02-10',
                               'DEV',
                               5500.00,
                               null,
                               101,
                               10 );

insert into employees values ( 1007,
                               'Sophia',
                               'Anderson',
                               'sophia.anderson@email.com',
                               '0752222222',
                               date '2021-09-15',
                               'SALES',
                               4200.00,
                               0.12,
                               103,
                               30 );

insert into employees values ( 1008,
                               'Daniel',
                               'Thomas',
                               'daniel.thomas@email.com',
                               null,
                               date '2020-05-05',
                               'HR',
                               4700.00,
                               null,
                               102,
                               20 );

insert into employees values ( 1009,
                               'Olivia',
                               'Jackson',
                               'olivia.jackson@email.com',
                               '0753333333',
                               date '2023-01-20',
                               'DEV',
                               6100.00,
                               null,
                               101,
                               10 );

insert into employees values ( 1010,
                               'James',
                               'White',
                               'james.white@email.com',
                               '0754444444',
                               date '2019-08-30',
                               'FIN',
                               7200.00,
                               null,
                               104,
                               40 );

insert into employees values ( 1011,
                               'Isabella',
                               'Harris',
                               'isabella.harris@email.com',
                               '0755555555',
                               date '2022-11-11',
                               'SALES',
                               3900.00,
                               0.20,
                               103,
                               30 );

insert into employees values ( 1012,
                               'William',
                               'Martin',
                               'william.martin@email.com',
                               null,
                               date '2021-03-18',
                               'DEV',
                               5800.00,
                               null,
                               101,
                               10 );

insert into employees values ( 1013,
                               'Mia',
                               'Thompson',
                               'mia.thompson@email.com',
                               '0756666666',
                               date '2020-07-25',
                               'HR',
                               4600.00,
                               null,
                               102,
                               20 );

insert into employees values ( 1014,
                               'Benjamin',
                               'Garcia',
                               'benjamin.garcia@email.com',
                               '0757777777',
                               date '2023-06-14',
                               'SALES',
                               4100.00,
                               0.08,
                               103,
                               30 );

insert into employees values ( 1015,
                               'Charlotte',
                               'Martinez',
                               'charlotte.martinez@email.com',
                               '0758888888',
                               date '2018-12-01',
                               'FIN',
                               7500.00,
                               null,
                               104,
                               40 );

commit;

--part 2

create or replace procedure adjust_salaries_by_commission is
---cursor pt parcurgere
   cursor c_employees is
   select employee_id,
          salary,
          commission_pct
     from employees;

   v_employee_id    employees.employee_id%type;
   v_salary         employees.salary%type;
   v_commission_pct employees.commission_pct%type;
   v_new_salary     employees.salary%type;
begin
   debug_utils.log_msg(
      'adjust_salaries_by_commission',
      10,
      'INFO',
      'Procedure started'
   );
   open c_employees;
   loop
    ---procesare logica
      fetch c_employees into
         v_employee_id,
         v_salary,
         v_commission_pct;
      exit when c_employees%notfound;
      debug_utils.log_msg(
         'adjust_salaries_by_commission',
         20,
         'INFO',
         'Processing employee_id = ' || v_employee_id
      );
      if v_commission_pct is not null then
         v_new_salary := v_salary + ( v_salary * v_commission_pct );
         debug_utils.log_msg(
            'adjust_salaries_by_commission',
            30,
            'INFO',
            'Commission found: ' || v_commission_pct
         );
      else
         v_new_salary := v_salary + ( v_salary * 0.02 );
         debug_utils.log_msg(
            'adjust_salaries_by_commission',
            40,
            'WARN',
            'Commission is NULL, default 2% applied'
         );
      end if;

      debug_utils.log_variable(
         'adjust_salaries_by_commission',
         45,
         'INFO',
         'v_new_salary',
         to_char(v_new_salary)
      );
      update employees
         set
         salary = v_new_salary
       where employee_id = v_employee_id;
      debug_utils.log_msg(
         'adjust_salaries_by_commission',
         50,
         'INFO',
         'Updated salary to ' || v_new_salary
      );
   end loop;

   close c_employees;
   debug_utils.log_msg(
      'adjust_salaries_by_commission',
      90,
      'INFO',
      'Procedure finished'
   );
   commit;
exception
   when others then
      debug_utils.log_error(
         'adjust_salaries_by_commission',
         99,
         'ERROR',
         sqlerrm
      );
      if c_employees%isopen then
         close c_employees;
      end if;
      rollback;
      raise;
end;
/
---aplicarea procedurii
begin
   debug_utils.enable_debug;
   adjust_salaries_by_commission;
end;
/

---query uri de testare
select employee_id,
       salary,
       commission_pct
  from employees
 order by employee_id;

select *
  from debug_log
 order by log_id;

select *
  from debug_log
 where log_level in ( 'WARN',
                      'ERROR' )
 order by log_id;
